### PR TITLE
Disabled performance warnings in non-debug mode

### PR DESCRIPTION
**Pull request by LeonMrBonnie**

### CODE REVIEW

**Comment by FabianTerhorst** [comment]
i don't know if its a good idea.

**Comment by FabianTerhorst** [comment]
people will come to ask in altv discord for bad fps.

**Comment by LeonMrBonnie** [comment]
This was already suggested many times because people don't like that it spams their console even outside of debug mode.
I suggested creating a console command to toggle it, but Hazard said I should just disable it in non-debug mode.

**Comment by LeonMrBonnie** [comment]
Actually, you even suggested this yourself as seen in https://github.com/altmp/altv-issues/issues/332

**Comment by tastydev** [comment]
I don´t like this aswell, cause u will not be able to see ur gamemode performing bad in some scenarios while running in production mode. Cause all production ready projects will have debug disabled for security reasons. I would be fine with it if it´s an extra flag instead of debug inside the cfg´s.

**Comment by FabianTerhorst** [comment]
> Actually, you even suggested this yourself as seen in [altmp/altv-issues#332](https://github.com/altmp/altv-issues/issues/332)

thats for server side.

**Comment by FabianTerhorst** [comment]
to not spam server console.

**Comment by LeonMrBonnie** [comment]
> 
> 
> > Actually, you even suggested this yourself as seen in [altmp/altv-issues#332](https://github.com/altmp/altv-issues/issues/332)
> 
> thats for server side.

Yes, and this is v8 helpers so it's both for client and for server. Making this for one side only would mean for some very ugly code

**Comment by FabianTerhorst** [comment]
Disabling it clientside makes it impossible to answer people that have low fps.

**Comment by FabianTerhorst** [comment]
And impossible for servers to fix performance problems from people they get log from.

**Comment by FabianTerhorst** [comment]
When people don't want that log clientside they should fix the performance.

**Comment by Heryshaf** [comment]
I think it should only be allowed in debug mode, devs usually test on dev and have their testers test on dev, they can know the reasons there and fix them.

**Comment by vadzz-dev** [comment]
When this warning happens it literally means the code has problems, and in non-debug it notifies a player that it's not an alt:V problem

**Pull request closed without merging**
