### PR TITLE
Add stringification of objects and arrays for log methods

### PR DESCRIPTION
**Pull request by LeonMrBonnie**

### CODE REVIEW

**Comment by LeonMrBonnie** [comment]
Draft because I need to test this a bit more.

**Comment by LeonMrBonnie** [comment]
Tested it. Works as intended.

Testcases:
```js
alt.log([5, 2, "test", { test: "", array: [4] }]);
alt.log("Test123");
alt.log(123);
alt.log({ empty: false })
alt.log(true);
```

**Comment by tastydev** [comment]
technically its´s a bad implementation cause JSON.stringify will block the event loop. So in heavy alt.log usage u will provoke desyncs and heavy performance issues.

**Comment by LeonMrBonnie** [comment]
> 
> 
> technically its´s a bad implementation cause JSON.stringify will block the event loop. So in heavy alt.log usage u will provoke desyncs and heavy performance issues.

That is to be expected. Logging to the console should not be done excessively in production anyway.
But what alternative would there be to JSON stringify?

**Comment by tastydev** [comment]
Doesn´t has to do anything with excessively logging. JSON.stringify is just toxic. Native parsing would be a better solution.

**Comment by LeonMrBonnie** [comment]
What would native parsing be? We write our own stringify function? That doesn't sound like a worth idea at all.

**Comment by LeonMrBonnie** [comment]
Btw I just benchmarked this. And the performance bottleneck is definitely not stringifying it.
When logging a 605k lines JSON file it only takes about 100ms to stringify it, but actually logging it to the console takes over 600ms.
So the problem here isn't stringify, stringify is definitely fast enough. But the console is not meant to be used for such excessive logging.

**Review by vadzz-dev — APPROVED** [review]

**Pull request merged**
