### PR TITLE
Rename functions of Vector classes to be more human friendly

### PR DESCRIPTION
**Pull request by KifKick**

### CODE REVIEW

**Comment by KifKick** [comment]
TODO: 

- add deprecation to old function names

**Comment by KifKick** [comment]
Deprecation done, waiting for review.

**Comment by Unnvaldr** [comment]
Replacing abbreviations with full names for operator alike methods doesn't have sense at all

**Comment by LeonMrBonnie** [comment]
I agree with Lhoerion here.
These methods basically function as operator overloads (as it doesn't exist in JS) and as such changing the name to the full name doesn't make a lot of sense.

**Pull request closed without merging**
